version: "3"

services:
  mysql:
    container_name: fc_dd_mysql
    #build: ./mysql
    image: mysql:5.7
    restart: always
    tty: true
    volumes:
      - ./mysql/dbdata:/var/lib/mysql/
      - ./mysql:/docker-entrypoint-initdb.d/
    environment:
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - net_dd

  nodejs:
    container_name: fc_dd_nodejs
    build: ./nodejs
    tty: true
    #aguardando container
    entrypoint: dockerize -wait tcp://mysql:3306 -timeout 20s node index.js
    volumes:
      - ./nodejs:/home/node/app
      - /home/node/app/node_modules #volume anonimo
    ports:
      - 3000:3000
    depends_on: #verificando se o container iniciou
      - mysql
    networks: #definindo grupo de rede
      - net_dd #rede criada para comunicacao do mysql e nodejs
      - net_dd_aux #rede criada para comunicacaod do nodejs e ngnix

  nginx:
    container_name: fc_dd_nginx
    build: ./nginx
    entrypoint: dockerize -wait http://nodejs:3000 -timeout 20s /docker-entrypoint.sh nginx -g 'daemon off;'
    ports:
      - 8000:80
    depends_on:
      - nodejs
    networks:
      - net_dd_aux

#criando redes
networks:
  net_dd:
    driver: bridge
    
  net_dd_aux:
    driver: bridge
